language: python
dist: xenial
matrix:
  include:
    - python: 2.7
    - python: 3.6
    - python: 3.7

addons:
  apt:
    packages:
    - gfortran

before_install:
  - pip install pytest-cov
  - pip install coveralls
  - pip install future
  - pip install matplotlib
  - pip install pysatCDF >/dev/null

  # Prepare modified pysat install
  - pip install numpy
  - cd ..
  - echo 'cloning pysat'
  - git clone https://github.com/pysat/pysat.git >/dev/null
  - echo 'installing pysat'
  - cd ./pysat
  - git checkout develop
  # set up data directory
  - mkdir /home/travis/build/pysatData
  # install pysat
  - python setup.py install >/dev/null

install:
  # install pysatMagVect
  - cd ../pysatMagVect
  - python setup.py develop

# command to run tests
script:
  - nosetests  -vs --with-coverage --cover-package=pysatMagVect

after_success:
  - coveralls
