language: python
dist: xenial
matrix:
  include:
    - python: 2.7
    - python: 3.6
    - python: 3.7
    - python: 3.8

addons:
  apt:
    packages:
    - gfortran

before_install:
  - pip install pytest-cov
  - pip install coveralls
  - pip install future
  # Install version specific packages for 2.7 and 3.5
  - pip install matplotlib
  - pip install apexpy
  - pip install numpy
  - pip install pysatCDF >/dev/null
  - pip install xarray==0.14.1
  - pip install pysat
 # set up data directory
  - mkdir /home/travis/build/pysatData
  - python -c 'import pysat; pysat.utils.set_data_dir("/home/travis/build/pysatData")'

install:
  # install OMMBV
  - python setup.py develop

# command to run tests
script:
  - nosetests  -vs --with-coverage --cover-package=OMMBV

after_success:
  - coveralls
