language: python
dist: xenial
matrix:
  include:
    - python: 2.7
    - python: 3.6
    - python: 3.7

services: xvfb
addons:
  apt:
    packages:
    - gfortran
    - libncurses5-dev

before_install:
  - pip install pytest-cov
  - pip install coveralls
  - pip install future
  - pip install matplotlib
  - pip install pysatCDF >/dev/null
  # Prepare modified pysat install
  - pip install numpy
  - cd ..
  - echo 'cloning pysat'
  - git clone https://github.com/pysat/pysat.git >/dev/null
  - echo 'installing pysat'
  - cd ./pysat
  - git checkout no_sgp4
  # set up data directory
  - mkdir /home/travis/build/pysat/pysatData
  # install pysat
  - cd /home/travis/build/pysat/pysat
  - python setup.py install >/dev/null
  - cd /home/travis/build/pysat/pysatMagVect

install:
  - python setup.py install

before_script:
  # set up display screen
  - export DISPLAY=:99.0
  - if [[ $TRAVIS_PYTHON_VERSION < "3.0" ]]; then
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

script:
  - pytest -vs --cov=pysatMagVect/

after_success:
  - coveralls
